name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          cd services/orchestrator
          python -m pip install -r requirements.txt
          python -m pip install ruff pytest
      - name: Lint
        run: |
          cd services/orchestrator
          ruff check .
      - name: Test
        run: |
          cd services/orchestrator
          pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: |
          cd apps/web
          npm ci || npm i
      - name: Build
        run: |
          cd apps/web
          npm run build --if-present
