name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          cd services/orchestrator
          python -m pip install -r requirements.txt
          python -m pip install ruff pytest
      - name: Lint
        run: |
          cd services/orchestrator
          ruff check .
      - name: Test
        run: |
          cd services/orchestrator
          pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: |
          cd apps/web
          npm ci || npm i
      - name: Build
        run: |
          cd apps/web
          npm run build --if-present

  orchestrator_smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps (orchestrator)
        run: |
          python -m pip install -U pip
          python -m pip install -r services/orchestrator/requirements.txt
      - name: Start orchestrator
        run: |
          nohup python -m uvicorn services.orchestrator.app.main:app --port 8000 --log-level warning &
          echo $! > uvicorn.pid
          # Wait for startup
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:8000/health >/dev/null 2>&1; then break; fi
            sleep 1
          done
      - name: Smoke test /health
        run: |
          curl -fsS http://127.0.0.1:8000/health
      - name: Stop orchestrator
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then kill $(cat uvicorn.pid) || true; fi
